backend:
  name: github
  repo: fernandes77/newer-rodrigofernand-es
  branch: main
  base_url: https://rodrigofernand.es # Your production domain
  auth_endpoint: api/auth

# Uncomment for local development (run: npx decap-server)
# local_backend: true

media_folder: "web/public/img/posts"
public_folder: "/img/posts"

collections:
  - name: "posts"
    label: "Posts"
    folder: "web/src/pages/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/PostLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Rodrigo Fernandes",
        }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
